### ISSUE TITLE
[feature request] is it possible to apply patches for YouTube's non-monotonous DTS and AAC HLS streams

### ISSUE THREAD

**Issue by eladkarako** [nanake/ffmpeg-tinderbox#1]
first, thanks for maintaining this project.

some time ago two patches were introduced to correctly handled some quirks in YT-encoded videos,  
https://github.com/yt-dlp/FFmpeg-Builds covers that information better.

would it be possible to apply those as well,  
(the current ffmpeg builds by yt-dlp sucks)

**Comment by nanake** [comment]
I'd rather refrain from adding 3rd party patch for ffmpeg.

**Comment by nanake** [comment]
take a look into their patch again, it's not complex to maintain. it's possible to do that. 

fwiw, the `AAC HLS streams` patch don't needed as it's already on ffmpeg. so, there's one patch left to apply, right?
