### ISSUE TITLE
nvenc, nvdec support

### ISSUE THREAD

**Issue by signumnova** [nanake/ffmpeg-tinderbox#14]
Hi there,

Just wondering if this build is compiled with nvidia sdk support enabled so that for example nvenc can be used?

Also is the Windows Desktop Dup API stuff compiled in there as well?

(I was trying to do a desktop capture to file using nvenc and was getting errors on the command line even though I was following examples from the current ffmpeg docs)

Cheers SN

**Comment by nanake** [comment]
nvenc and nvdec are supported.

```
ffmpeg -encoders | grep nv

 V....D av1_nvenc            NVIDIA NVENC av1 encoder (codec av1)
 V....D h264_nvenc           NVIDIA NVENC H.264 encoder (codec h264)
 V....D hevc_nvenc           NVIDIA NVENC hevc encoder (codec hevc)
```

> Also is the Windows Desktop Dup API stuff compiled in there as well?

wfm using command 

`ffmpeg -filter_complex ddagrab=0,hwdownload,format=bgra -c:v libx264 -crf 20 output.mkv `
https://trac.ffmpeg.org/wiki/Capture/Desktop#UseWindows8DesktopDuplicationAPI

> I was trying to do a desktop capture to file using nvenc and was getting errors [...]

I don't do ffmpeg help desk. You could probably get help from ffmpeg-user mail list.
