### ISSUE TITLE
Stopped working on Windows 7

### ISSUE THREAD

**Issue by sergeevabc** [nanake/ffmpeg-tinderbox#15]
Windows 7 x64.

Latest version [ffmpeg-N-115182-git-0d9591841](https://github.com/nanake/ffmpeg-tinderbox/releases/tag/build-2024-05-11-21-19-n115182) throws an error `0xc0000005`.

![2024-0512-1312 ffmpeg nanake error](https://github.com/nanake/ffmpeg-tinderbox/assets/373718/4a888749-0015-4a5c-b713-e6a9b12ff416)

Previous version [ffmpeg-N-115171-git-5afe734b6](https://github.com/nanake/ffmpeg-tinderbox/releases/tag/build-2024-05-10-21-21-n115171) works fine.

**Comment by nanake** [comment]
I had removed support for Windows 7 since mid-2023, so I was surprised it could run on Windows 7 for long.

If upgrading your system is impossible, I can only suggest you could live with the last known good version.

**Comment by nanake** [comment]
I had removed support for Windows 7 since mid-2023, so I was surprised it could run on Windows 7 for long.

If upgrading your system is impossible, I can only suggest you could live with the last known good version.

**Comment by sergeevabc** [comment]
Official FFMPEG is compatible with Windows 7, so there is nothing to change within the code. That's why it is reasonable to assume that you changed something in the compilation strategy, some flag or something like that, which allows fewer or more poor chaps to enjoy the application. Obviously, when an app serves more chaps, it's better, so why artificially deprive us of this tool? Please, don't become a traitor, just compare the two mentioned versions, they're recent.

**Comment by nicolaasjan** [comment]
@sergeevabc
Checkout [AnimMouse/ffmpeg-autobuild](https://github.com/AnimMouse/ffmpeg-autobuild) `2024-05-16 15:34 d4083ec`.
That one still works on Windows 7. 🙂

The executable is quite smaller in size (98.6MB), so it probably has fewer advanced capabilities.

```
ffmpeg version git-2024-05-16-d4083ec-ffmpeg-windows-build-helpers Copyright (c) 2000-2024 the FFmpeg developers
built with gcc 10.2.0 (GCC)
configuration: --pkg-config=pkg-config --pkg-config-flags=--static --extra-version=ffmpeg-windows-build-helpers --enable-version3 --disable-debug --disable-w32threads --arch=x86_64 --target-os=mingw32 --cross-prefix=/home/runner/work/ffmpeg-autobuild/ffmpeg-autobuild/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32- --enable-libcaca --enable-gray --enable-libtesseract --enable-fontconfig --enable-gmp --enable-libass --enable-libbluray --enable-libbs2b --enable-libflite --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libvorbis --enable-libwebp --enable-libzimg --enable-libzvbi --enable-libmysofa --enable-libopenjpeg --enable-libopenh264 --enable-libvmaf --enable-libsrt --enable-libxml2 --enable-opengl --enable-libdav1d --enable-gnutls --enable-libsvtav1 --enable-libvpx --enable-libaom --enable-nvenc --enable-nvdec --extra-libs=-lz --extra-libs=-lpng --extra-libs=-lm --extra-libs=-lfreetype --extra-libs=-lshlwapi --extra-libs=-lmpg123 --extra-libs=-lpthread --extra-cflags=-DLIBTWOLAME_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCACA_STATIC --enable-amf --enable-libmfx --enable-libaribcaption --enable-gpl --enable-frei0r --enable-librubberband --enable-libvidstab --enable-libx264 --enable-libx265 --enable-avisynth --enable-libaribb24 --enable-libxvid --enable-libdavs2 --enable-libxavs2 --enable-libxavs --extra-cflags='-mtune=generic' --extra-cflags=-O3 --enable-static --disable-shared --prefix=/home/runner/work/ffmpeg-autobuild/ffmpeg-autobuild/ffmpeg-source --enable-nonfree --enable-libfdk-aac --enable-decklink
libavutil      59. 17.100 / 59. 17.100
libavcodec     61.  5.103 / 61.  5.103
libavformat    61.  3.103 / 61.  3.103
libavdevice    61.  2.100 / 61.  2.100
libavfilter    10.  2.101 / 10.  2.101
libswscale      8.  2.100 /  8.  2.100
libswresample   5.  2.100 /  5.  2.100
libpostproc    58.  2.100 / 58.  2.100
```

**Comment by sergeevabc** [comment]
Yes, it seems @AnimMouse is a hero of our time who stays true to the mission of helping humanity through technology and not dividing it into more privileged and less fortunate users.

Regarding @nanake's stubbornness, it reminds me of the famous [Charlie Chaplin](https://www.youtube.com/watch?v=J7GY1Xg6X20)'s speech (1940): “…We have developed speed but we have shut ourselves in: machinery that gives abundance has left us in want. Our knowledge has made us cynical, our cleverness hard and unkind. We think too much and feel too little: more than machinery we need humanity…”.
