### ISSUE TITLE
audio loss randomly after couple of hours

### ISSUE THREAD

**Issue by ansariatif** [nanake/ffmpeg-tinderbox#17]
hi,
i am using decklink duo and decklink driver 14.2 on windows 10 i7 13th generation. with following command

ffmpeg -f decklink -channels 2 -i "DeckLink Duo (1)" -filter_complex "[0:v]scale=720:576,drawtext@ticker='textfile=C:\Users\Scrl-001\Documents\test ticker.txt:reload=1:expansion=none:fontfile=C\:/Windows/Fonts/ARIALN.TTF:y=452:x=w-mod(60*t,tw+w) : fontcolor=#000000@1: fontsize=54'[test];[test]scale@vid=720:576:eval=frame,fps=25[out]" -map 0:a -map "[out]" -f decklink -format_code pal -s 720x576 -r 25000/1000 -pix_fmt uyvy422 -c:a pcm_s16le -ar 48000 -ac 2 -field_order tt "DeckLink Duo (2)"

after couple of hours no audio in output .

log shows
decklink there are not enough buffered video frames. video may misbehave!
decklink there's no buffered audio. audio will misbehave!

**Comment by nanake** [comment]
that means buffer underrun. you better ask questions on support channel, the ffmpeg-user mailing list.
